services:

  frontend-dev:
    build: ./frontend
    restart: always
    networks:
      - partytracker_dev_net

  backend-dev:
    build: ./backend
    restart: always
    env_file:
      - .env.dev
    depends_on:
      db-dev:
        condition: service_healthy
    networks:
      - partytracker_dev_net

  db-dev:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - partytracker_dev_net

volumes:
  postgres_data_dev:

networks:
  partytracker_dev_net:
    name: partytracker_dev_net
    driver: bridge

