limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

server {
    listen 80;
    server_name partytracker.fun www.partytracker.fun;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name partytracker.fun www.partytracker.fun;

    ssl_certificate /etc/letsencrypt/live/partytracker.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/partytracker.fun/privkey.pem;

# Приховати версію Nginx
    server_tokens off;

# Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# Rate limiting
    limit_req zone=api burst=20 nodelay;

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location / {
        proxy_pass http://frontend:3000/;
    }
}


server {
    listen 80;
    server_name dev.partytracker.fun;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dev.partytracker.fun;

    ssl_certificate /etc/letsencrypt/live/dev.partytracker.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.partytracker.fun/privkey.pem;

    server_tokens off;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    limit_req zone=api burst=20 nodelay;

    location /api/ {
        proxy_pass http://backend-dev:8000/;
    }

    location / {
        proxy_pass http://frontend-dev:3000/;
    }
}
