server {
    listen 80;
    server_name partytracker.fun www.partytracker.fun;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name partytracker.fun www.partytracker.fun;

    ssl_certificate /etc/letsencrypt/live/partytracker.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/partytracker.fun/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location / {
        proxy_pass http://frontend:3000/;
    }
}
